name:                adventOfCode2020
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck
- containers


library:
  source-dirs: src

executables:
  adventOfCode2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - adventOfCode2020

tests:
  adventOfCode2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - adventOfCode2020
